### ISSUE TITLE
How Do I Integrate this with PIMSim?

### ISSUE THREAD

**Issue by Sayan3116** [tactcomplabs/gc64-hmcsim#5]
Please provide a detailed description as to how can someone integrate this with PIMSim.

**Comment by jleidel** [comment]
I would suggest looking at how PIMSim functions.  Its an extension to Gem5, so the logical answer would be to integrate HMCSim directly into the Gem5 memory layer.

There are two API layers in HMCSim.  The original, or "full" API (which is used to integrate HMCSim with SST) provides every possible configuration option of the target HMC device or devices.  Its also rather verbose.  An example of using that API can be found here: https://github.com/tactcomplabs/gc64-hmcsim/tree/master/test/hmc_physrand

The second API, or "simple" API, is a set of wrapper functions that simplify the interface for users.  The full API (above) requires users to manually build HMC packets using specific functions.  The simple API does all this for you.  A good example of the simple API can be found here: https://github.com/tactcomplabs/gc64-hmcsim/tree/master/test/simple_api/simple4GBstall/src
