### ISSUE TITLE
 How do I execute trace file by this?

### ISSUE THREAD

**Issue by GFLY-PAPER** [tactcomplabs/gc64-hmcsim#6]
The application trace file obtained through the pin tool, how to use  the simulator to execute this trace file. Can you give me an example? thank you!

**Comment by jleidel** [comment]
HMC-Sim will not ingest Pin traces directly.  It is only designed to function as a backend memory simulation tool.  If you are firm in using Pin to generate traces, I would suggest using a larger infrastructure such as Sandia’s SST (http://sst-simulator.org).  This is a PDES that supports Pin as a CPU model (Ariel) and HMC-Sim as the backend memory model. This will allow you to pass cycle-driven traces from Pin to HMC-Sim
