### ISSUE TITLE
Why is it so fast to request a data？

### ISSUE THREAD

**Issue by GFLY-PAPER** [tactcomplabs/gc64-hmcsim#7]
hello,I'm a little confused，I send a request to hmcsim,Three cycles later, I receive a response,Why is it so fast to request a data？

**Comment by jleidel** [comment]
The latency to get a response back from the device depends upon the following factors:

- The configuration of the device.  This includes the queue depth, number of vaults, links and number of DRAMs per device.
- The link configuration.  Are you sending the request down a link that is co-located with the target vault (eg, reducing the route time across the HMC logic layer)?
- The dram latency.  What are you using as the DRAM latency?  The default is 2 cycles.  
- The device congestion.  How many requests are you sending an in what patterns?  If you send a single request and there are no other requests pending, then your queuing delayed is minimized.

**Comment by GFLY-PAPER** [comment]
Thank you very much for receiving your reply，I use the default settings for all configurations, but I have not seen where I can change Dram latency，It seems that there is no configuration that can be modified，Can you give some hints？ Thanks!

**Comment by jleidel** [comment]
You can set the DRAM latency using the following function: 
`int hmcsim_init_dram_latency( struct hmcsim_t *hmc, uint32_t latency );
`
...where *hmc is a pointer to an initialized HMC object and the latency value is measured in cycles.

**Comment by GFLY-PAPER** [comment]
OK,Thank you very much!
