### ISSUE TITLE
How to get energy consumption

### ISSUE THREAD

**Issue by GFLY-PAPER** [tactcomplabs/gc64-hmcsim#8]
hello，How do I get energy consumption data when I run it.

**Comment by jleidel** [comment]
Look at the following example.  You need to load a power configuration file that definitions the power utilization for each HMC sub component.  These values will be utilized to accumulate power statistics for individual components and the entire device.  


https://github.com/tactcomplabs/gc64-hmcsim/tree/master/test/stream_power_config

**Comment by GFLY-PAPER** [comment]
After I use the hmcsim_read_config() function to configure, there is still no output of energy consumption results after running. Is the corresponding output function not provided?

**Comment by jleidel** [comment]
You're likely not enabling the tracing in the API.  In the same test, look at the execute_test.c file.  Specifically lines 122-129.  This is the code required to open an output file, send the handle to HMC-Sim and enable all the tracing.
